[versions]
ktor-client = "1.5.3"
kotlin = "1.5.10"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor-client" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor-client" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor-client" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor-client" }
konsume-xml = { module = "com.gitlab.mvysny.konsume-xml:konsume-xml", version = "0.14" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.2.1" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[bundles]
ktor-client = ["ktor-client-core", "ktor-client-cio", "ktor-client-logging"]